import {presets,slots,recipeById,totals,calories,generate,groceries,swap} from './planner.js';
import {assignmentAt,calculateBatch} from './batches.js';
import {nutritionFields} from './products.js';
const $=id=>document.getElementById(id), key='gather-meal-plan-v1';
const fields=['week','diet','protein','carbs','fat','people','minutes','dinner','prep','exclude'];
const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n.toFixed(1));
const dateString=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const monday=new Date();monday.setDate(monday.getDate()-((monday.getDay()+6)%7));
let state={settings:{week:dateString(monday),diet:'balanced',...presets.balanced,people:1,minutes:60,dinner:'19:00',prep:'6',exclude:''},plan:[],checked:[]};
let savedProducts=[],savedBatches=[];
try{const saved=JSON.parse(localStorage.getItem(key));if(saved?.settings&&Array.isArray(saved.plan)&&saved.plan.length===7&&saved.plan.every(d=>Array.isArray(d)&&d.every(m=>recipeById(m.id)&&[0.75,1,1.25,1.5].includes(m.portion))))state={...state,...saved,settings:{...state.settings,...saved.settings},checked:Array.isArray(saved.checked)?saved.checked:[]};}catch{}
for(const f of fields)$(f).value=state.settings[f];
function readSettings(){return Object.fromEntries(fields.map(f=>[f,['protein','carbs','fat','people','minutes'].includes(f)?Number($(f).value):$(f).value]));}
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('save-status').textContent='Your plan is saved locally.';}catch{$('save-status').textContent='Local saving is unavailable. Keep this tab open or print your plan.';}}
function dates(){const start=new Date(state.settings.week+'T12:00:00');return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});}
function batchMeal(day,index){return assignmentAt(savedBatches,dateString(dates()[day]),slots[index]);}
function dayNumbers(day){const sums={p:0,c:0,f:0,calories:0};for(let j=0;j<3;j++){const custom=batchMeal(day,j);if(custom){const c=calculateBatch(custom.batch,savedProducts),factor=custom.assignment.portions/state.settings.people;for(const [key,nutrient]of Object.entries({p:'protein',c:'carbs',f:'fat',calories:'calories'})){if(sums[key]===null)continue;sums[key]=c.perPortion[nutrient]===null?null:sums[key]+c.perPortion[nutrient]*factor;}}else{const m=state.plan[day]?.[j];if(!m)continue;const t=totals([m]);for(const k of ['p','c','f'])if(sums[k]!==null)sums[k]+=t[k];if(sums.calories!==null)sums.calories+=calories(t);}}return sums;}
const nutrientText=value=>value===null?'Incomplete':Math.round(value);
function mealCard(day,j){const custom=batchMeal(day,j);if(custom){const {batch,assignment}=custom,c=calculateBatch(batch,savedProducts),factor=assignment.portions/state.settings.people;return `<div class="meal"><span class="meal-label">${slots[j]}</span> <span class="batch-chip">Batch meal</span><button class="meal-name" data-batch-recipe="${day},${j}">🍽️ ${escape(batch.name)}</button><div class="meal-meta">${assignment.portions} portion(s) for the household · ${fmt(factor)} / person<br>P ${nutrientText(c.perPortion.protein===null?null:c.perPortion.protein*factor)} · C ${nutrientText(c.perPortion.carbs===null?null:c.perPortion.carbs*factor)} · F ${nutrientText(c.perPortion.fat===null?null:c.perPortion.fat*factor)} g</div><div class="meal-bottom"><span class="field-note">Edit assignments in Batch meals</span></div></div>`;}const m=state.plan[day]?.[j];if(!m)return `<div class="meal"><span class="meal-label">${slots[j]}</span><p>No generated meal.</p></div>`;const r=recipeById(m.id);return `<div class="meal"><span class="meal-label">${slots[j]}</span><button class="meal-name" data-recipe="${day},${j}"><span class="meal-emoji">${r.emoji}</span>${r.name}</button><div class="meal-meta">${r.time} min cooking · ${m.portion}× portion / person<br>P ${Math.round(r.p*m.portion)} · C ${Math.round(r.c*m.portion)} · F ${Math.round(r.f*m.portion)} g</div><div class="meal-bottom"><button class="swap" data-swap="${day},${j}" ${m.locked?'disabled':''}>↻ Swap</button><button class="lock ${m.locked?'locked':''}" data-lock="${day},${j}" aria-pressed="${m.locked}">${m.locked?'● Locked':'○ Lock'}</button></div></div>`;}
function render(){
 const s=state.settings,ds=dates();
 $('week-title').textContent=`${ds[0].toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${ds[6].toLocaleDateString(undefined,{month:'short',day:'numeric'})}`;
 $('calorie-target').textContent=`${calories({p:Number($('protein').value),c:Number($('carbs').value),f:Number($('fat').value)}).toLocaleString()} kcal / day from your targets`;
 const notices=[];
 const empty=state.plan.map((d,i)=>d.length?null:ds[i].toLocaleDateString(undefined,{weekday:'long'})).filter(Boolean);
 if(empty.length)notices.push(`No feasible menu for ${empty.join(', ')}. Increase your daily cooking time, change exclusions, or unlock meals and rebuild.`);
 const off=state.plan.filter((d,index)=>d.length&&['p','c','f'].some((k,i)=>dayNumbers(index)[k]!==null&&Math.abs(dayNumbers(index)[k]-s[['protein','carbs','fat'][i]])>Math.max(s[['protein','carbs','fat'][i]]*0.2,5))).length;
 if(off)notices.push(`${off} day${off===1?'':'s'} fall outside a 20% macro tolerance (minimum 5 g). This small recipe library cannot meet every target; adjust targets, portions, or meals. Presets are preferences, not strict diet guarantees.`);
 if(s.people>1)notices.push('Cooking times are estimates for one recipe portion. Larger batches may need extra time or equipment; review the schedule for your household.');
 const weekDates=ds.map(dateString);if(savedBatches.some(b=>b.assignments.some(a=>weekDates.includes(a.date))))notices.push('Batch assignments replace generated meals and remain when you rebuild the week. Missing label data makes daily totals incomplete. Batch meals are manually chosen; diet and ingredient-exclusion checks apply to generated recipes.');
 $('notices').innerHTML=notices.map(n=>`<div class="notice">${escape(n)}</div>`).join('');
 $('meals').innerHTML=state.plan.map((day,i)=>{const t=dayNumbers(i);return `<article class="day"><div class="day-head"><h3>${ds[i].toLocaleDateString(undefined,{weekday:'long'})}<span>${ds[i].toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></h3><span class="day-total">${nutrientText(t.calories)} kcal · P ${nutrientText(t.p)} · C ${nutrientText(t.c)} · F ${nutrientText(t.f)} g</span></div><div class="meal-grid">${slots.map((_,j)=>mealCard(i,j)).join('')}</div></article>`;}).join('');
 renderPrep(ds);renderGroceries();
}
function timeLabel(min){return `${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`;}
function renderPrep(ds){
 const s=state.settings;
 const shop=new Date(ds[0]);const selected=Number(s.prep);const offset=((shop.getDay()+6)%7-selected+7)%7;shop.setDate(shop.getDate()-offset);
 const shopLabel=shop.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});
 $('prep-view').innerHTML=`<p class="view-intro">A suggested rhythm based on your ${s.minutes}-minute daily cooking budget. Breakfast and lunch times are flexible; dinner finishes at ${escape(s.dinner)}. Cooking durations assume parallel passive cooking. Review recipe instructions and safe handling before preparing food.</p><article class="schedule-card"><div class="schedule-icon">🛒</div><div><h3>${shopLabel} · plan & shop</h3><p>Review your pantry and the grocery list before the first meal. This is the most recent selected shopping day on or before the week starts. Choose a real shopping window yourself; travel and checkout time are not included. Buy delicate ingredients closer to use, or choose a midweek top-up.</p></div></article>`+state.plan.map((day,i)=>{
 if(!day.length)return '';const dinner=recipeById(day[2].id);const [h,m]=s.dinner.split(':').map(Number);const end=h*60+m;const start=end-dinner.time;const t=totals(day);
 const fresh=totals(day.filter((_,j)=>!batchMeal(i,j)));const customDinner=batchMeal(i,2);
 return `<article class="schedule-card"><div class="schedule-icon">${i===3?'🌱':'🍽️'}</div><div><h3>${ds[i].toLocaleDateString(undefined,{weekday:'long'})} · ${fresh.time} min fresh cooking</h3><p>${slots.map((slot,j)=>{const custom=batchMeal(i,j);return custom?`${slot}: ${escape(custom.batch.name)} · allocated batch portions`:`${slot}: ${recipeById(day[j].id).time} min`;}).join(' · ')}<br>${customDinner?`Dinner at ${escape(s.dinner)} uses batch portions; account for reheating or finishing time.`:`Dinner: ${timeLabel((start+1440)%1440)}${start<0?' on the previous day':''}–${escape(s.dinner)} · ${dinner.name}.`} Cook crisp toppings close to serving for texture.${i===3?' Review remaining ingredients today and top up as needed.':''}<br>Fresh cooking times exclude batch preparation, thawing, reheating, cooling, cleanup and calendar availability.</p></div></article>`;
 }).join('');
 const week=ds.map(dateString);$('prep-view').innerHTML+=savedBatches.filter(b=>b.assignments.some(a=>week.includes(a.date))).map(b=>{const first=[...b.assignments].sort((a,z)=>a.date.localeCompare(z.date)||slots.indexOf(a.slot)-slots.indexOf(z.slot))[0];return `<article class="schedule-card"><div class="schedule-icon">🥣</div><div><h3>Batch preparation · ${escape(b.name)}</h3><p>Prepare ${b.portions} portions before ${first.date} ${first.slot}.${b.prepMinutes?` Your entered preparation estimate is ${b.prepMinutes} minutes.`:' Enter a preparation estimate in Batch meals.'} Choose an actual preparation window and follow the products’ storage guidance; this plan does not determine safe storage or reheating intervals.</p></div></article>`;}).join('');
}
function renderGroceries(){const freshPlan=state.plan.map((day,i)=>day.filter((_,j)=>!batchMeal(i,j)));const items=groceries(freshPlan,state.settings.people);const week=dates().map(dateString);const pooled=new Map();for(const batch of savedBatches.filter(b=>b.assignments.some(a=>week.includes(a.date))))for(const x of calculateBatch(batch,savedProducts).shopping){const prev=pooled.get(x.product?.id)||{product:x.product,packages:0,known:true};prev.known&&=x.known;prev.packages+=x.packages;pooled.set(x.product?.id,prev);}const purchases=[...pooled.values()];$('grocery-count').textContent=items.length+purchases.length;const groups=[...new Set(items.map(i=>i.category))];$('groceries').innerHTML=`<p class="view-intro">Generated recipe ingredients plus whole-batch purchases for batches assigned this week. Replaced generated meals are excluded. Check off items already on hand or bought.</p>`+groups.map(group=>`<section class="grocery-group"><h3>${group}</h3>${items.filter(i=>i.category===group).map(i=>`<label class="grocery-row"><input type="checkbox" data-grocery="${escape(i.key)}" ${state.checked.includes(i.key)?'checked':''}><span>${i.name}</span><span class="amount">${fmt(i.amount)} ${i.unit}</span></label>`).join('')}</section>`).join('')+(purchases.length?`<section class="grocery-group"><h3>Food Library products · scheduled batches</h3><p class="field-note">Requirements cover each whole batch once, including portions not yet scheduled. Purchases assume no stock on hand; no pantry inventory is adjusted.</p>${purchases.map(x=>{const key='batch-product|'+x.product.id;return `<label class="grocery-row"><input type="checkbox" data-grocery="${key}" ${state.checked.includes(key)?'checked':''}><span>${escape(x.product.name)}<br><small>${x.known?`Use ${fmt(x.packages)} packages; ${fmt(Math.ceil(x.packages-1e-9)-x.packages)} package unused after purchase`:'Package conversion unknown'}</small></span><span class="amount">${x.known?Math.ceil(x.packages-1e-9):'?'} packages</span></label>`;}).join('')}</section>`:'');}
function showRecipe(day,index){const m=state.plan[day][index],r=recipeById(m.id),scale=m.portion*state.settings.people;$('recipe-content').innerHTML=`<p class="eyebrow">${r.slot.toUpperCase()} · ${r.time} MIN</p><h2>${r.emoji} ${r.name}</h2><p>Ingredients for ${state.settings.people} ${state.settings.people===1?'person':'people'} at ${m.portion}× portion size.</p><ul>${r.ingredients.map(i=>`<li>${fmt(i.amount*scale)} ${i.unit} ${i.name.toLowerCase()}</li>`).join('')}</ul><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol><p class="field-note">Nutrition is an illustrative estimate for the recipe, not calculated from a verified food database. Cook animal products fully using authoritative safe-temperature guidance. Follow package directions for storage; this app does not supply shelf-life estimates.</p>`;$('recipe-dialog').showModal();}
function activate(tab){document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});$('meals').hidden=tab!=='meals';$('prep-view').hidden=tab!=='prep';$('groceries').hidden=tab!=='groceries';$('products').hidden=tab!=='products';$('batches').hidden=tab!=='batches';$('notices').hidden=['products','batches'].includes(tab);}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.tab)));
$('settings').addEventListener('submit',e=>{e.preventDefault();const next=readSettings();const removed=state.plan.flat().filter(m=>m.locked).length;const previous=state.plan;state.settings=next;state.plan=generate(next,previous);state.checked=[];save();render();const kept=state.plan.flat().filter(m=>m.locked).length;if(kept<removed)$('notices').insertAdjacentHTML('afterbegin','<div class="notice">Some locked meals were removed because the new exclusions, diet, or time budget made them infeasible.</div>');});
$('diet').addEventListener('change',()=>{for(const f of ['protein','carbs','fat'])$(f).value=presets[$('diet').value][f];updateCalories();});
function updateCalories(){$('calorie-target').textContent=`${calories({p:Number($('protein').value),c:Number($('carbs').value),f:Number($('fat').value)}).toLocaleString()} kcal / day from your targets`;}
for(const f of ['protein','carbs','fat'])$(f).addEventListener('input',updateCalories);
$('meals').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const action=['recipe','swap','lock','batchRecipe'].find(k=>b.dataset[k]);if(!action)return;const [day,index]=b.dataset[action].split(',').map(Number);if(action==='batchRecipe'){const {batch,assignment}=batchMeal(day,index),c=calculateBatch(batch,savedProducts);$('recipe-content').innerHTML=`<p class="eyebrow">BATCH MEAL · ${assignment.portions} HOUSEHOLD PORTIONS</p><h2>${escape(batch.name)}</h2><p>This batch makes ${batch.portions} meal portions. Ingredients below are for the entire batch.</p><ul>${c.rows.map(r=>`<li>${r.amount} ${r.unit} · ${escape(r.product?.name||'Missing product')}</li>`).join('')}</ul><p>${escape(batch.notes||'Add preparation instructions in Batch meals.')}</p><p class="field-note">Edit the recipe and assignments in Batch meals. Nutrition uses product labels; package serving counts may be approximate.</p>`;$('recipe-dialog').showModal();return;}if(action==='recipe'){showRecipe(day,index);return;}if(action==='lock')state.plan[day][index].locked=!state.plan[day][index].locked;if(action==='swap'){if(!swap(state.plan,day,index,state.settings)){$('notices').insertAdjacentHTML('afterbegin','<div class="notice">No alternative meal fits the current exclusions and cooking budget.</div>');return;}state.checked=[];}save();render();});
$('groceries').addEventListener('change',e=>{const k=e.target.dataset.grocery;if(!k)return;state.checked=state.checked.filter(x=>x!==k);if(e.target.checked)state.checked.push(k);save();});
$('close-dialog').addEventListener('click',()=>$('recipe-dialog').close());
$('print').addEventListener('click',()=>window.print());
if(!state.plan.length)state.plan=generate(state.settings);render();save();
document.addEventListener('gather-batches-updated',e=>{savedProducts=e.detail.products;savedBatches=e.detail.batches;render();});
