import {calculateBatch,validateBatch,batchUnits} from './batches.js';
import {nutritionFields} from './products.js';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>n===null?'Incomplete':Number(n.toFixed(2)),money=n=>n===null?'Incomplete':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
let products=[],batches=[],editing=null;
$('batches').innerHTML=`<div class="library-heading"><div><p class="eyebrow">COOK ONCE · PORTION YOUR WAY</p><h2>Batch meals</h2></div></div><p class="view-intro">Combine Food Library items into one batch, then divide it into meal portions. Label servings and meal portions are separate. Saved batch calculations use the latest saved product prices and labels.</p><section class="product-panel"><form id="batch-form"><div class="two-fields"><label>Batch name<input id="batch-name" required placeholder="Waffles, sausage & eggs"></label><label>Makes how many meal portions?<input id="batch-portions" type="number" min="1" max="1000" value="4" required></label></div><label>Total batch prep time · minutes (optional)<input id="batch-prep-minutes" type="number" min="1" step="any" placeholder="Enter your expected prep time"></label><h3>Ingredients for the entire batch</h3><div id="batch-ingredients"></div><button type="button" class="secondary" id="add-batch-ingredient">＋ Add ingredient</button><p class="field-note">Use fractions of packages or label servings. For grams or pieces, enter the matching amount in a whole package yourself. Keep raw and cooked weights consistent with your package label.</p><label>Instructions / notes<textarea id="batch-notes" rows="2"></textarea></label><div id="batch-preview"></div><div class="product-actions"><button type="submit" class="primary">Save batch <span>＋</span></button><button type="button" class="secondary" id="clear-batch">New batch</button></div><p id="batch-status" role="status" aria-live="polite"></p></form></section><div class="library-heading"><h2>Saved batches</h2></div><div id="batch-list"></div>`;
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed.');return data;}
function status(s,error=false){$('batch-status').textContent=s;$('batch-status').className=error?'product-error':'product-success';}
function addRow(row={}){const div=document.createElement('div');div.className='batch-ingredient';div.innerHTML=`<label>Food Library product<select class="batch-product" required><option value="">Choose an item…</option>${products.map(p=>`<option value="${p.id}" ${p.id===row.productId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Amount used<input class="batch-amount" type="number" min="0.001" step="any" value="${row.amount??1}" required></label><label>Unit<select class="batch-unit">${batchUnits.map(u=>`<option value="${u}" ${u===(row.unit||'packages')?'selected':''}>${u==='servings'?'label servings':u}</option>`).join('')}</select></label><label class="conversion-field" ${!['grams','pieces'].includes(row.unit)?'hidden':''}>Grams / pieces in whole package<input class="batch-conversion" type="number" min="0.001" step="any" value="${row.unitsPerPackage??''}"></label><button type="button" class="lock remove-ingredient" aria-label="Remove ingredient">×</button>`;$('batch-ingredients').append(div);preview();}
function read(){return {id:editing?.id,name:$('batch-name').value,portions:Number($('batch-portions').value),prepMinutes:$('batch-prep-minutes').value,notes:$('batch-notes').value,assignments:editing?.assignments||[],ingredients:[...document.querySelectorAll('.batch-ingredient')].map(row=>({productId:row.querySelector('.batch-product').value,amount:Number(row.querySelector('.batch-amount').value),unit:row.querySelector('.batch-unit').value,unitsPerPackage:row.querySelector('.batch-conversion').value}))};}
function summary(batch,full=false){const c=calculateBatch(batch,products);const core=['calories','protein','carbs','fat','sodium'];const unknown=core.filter(k=>c.nutrition[k]===null);return `<div class="batch-summary"><div><small>Makes</small><strong>${batch.portions} portions</strong></div><div><small>Ingredients used</small><strong>${money(c.cost)}</strong></div><div><small>Cost / meal portion</small><strong>${money(c.costPerPortion)}</strong></div><div><small>Buy whole packages*</small><strong>${money(c.purchaseCost)}</strong></div></div>${unknown.length?'<p class="notice">Some product labels or prices are missing. Incomplete values include an unknown contribution; known subtotals are shown separately below.</p>':''}<table class="nutrition-table"><thead><tr><th>Nutrient</th><th>Whole batch</th><th>Each meal portion</th>${unknown.length?'<th>Known subtotal / portion</th>':''}</tr></thead><tbody>${nutritionFields.filter(([k])=>full||core.includes(k)).map(([k,l,u])=>`<tr><th>${l}</th><td>${num(c.nutrition[k])}${c.nutrition[k]===null?'':` ${u}`}</td><td>${num(c.perPortion[k])}${c.perPortion[k]===null?'':` ${u}`}</td>${unknown.length?`<td>${Number((c.knownNutrition[k]/batch.portions).toFixed(2))} ${u}${c.nutrition[k]===null?' + unknown':''}</td>`:''}</tr>`).join('')}</tbody></table><p class="field-note">*Purchase cost assumes no packages on hand. Label rounding and approximate label serving counts affect totals. Missing nutrients remain incomplete rather than zero.</p>`;}
function preview(){try{const b=validateBatch(read(),products);$('batch-preview').innerHTML=summary(b);}catch{$('batch-preview').innerHTML='<p class="field-note">Choose ingredients and enter quantities to see batch and per-portion totals.</p>';}}
function edit(batch){editing=batch;$('batch-name').value=batch?.name||'';$('batch-portions').value=batch?.portions||4;$('batch-prep-minutes').value=batch?.prepMinutes??'';$('batch-notes').value=batch?.notes||'';$('batch-ingredients').innerHTML='';for(const row of batch?.ingredients||[{}])addRow(row);preview();}
function display(){const date=$('week').value;$('batch-list').innerHTML=batches.length?batches.map(b=>{const c=calculateBatch(b,products);return `<article class="product-panel saved-batch"><div class="product-card-top"><div><p class="eyebrow">${c.remaining} OF ${b.portions} PORTIONS UNSCHEDULED</p><h3>${esc(b.name)}</h3></div><button type="button" class="secondary" data-edit-batch="${b.id}">Edit batch</button></div><ul class="batch-recipe-items">${c.rows.map(r=>`<li>${r.amount} ${r.unit} · ${esc(r.product?.name||'Missing product')}<small>${r.packages===null?'Package conversion missing':`${num(r.packages/b.portions)} package per meal portion`}</small></li>`).join('')}</ul>${summary(b)}<details><summary>All nutrients</summary>${summary(b,true)}</details><details><summary>Whole-package shopping & remainder</summary><ul>${c.shopping.map(x=>`<li>${esc(x.product?.name||'Missing product')}: use ${num(x.known?x.packages:null)} packages; buy ${num(x.buyPackages)}; ${num(x.remainderPackages)} package left unopened/unused.</li>`).join('')}</ul><p class="field-note">This is a purchase estimate, not a pantry inventory adjustment. Recipe-level batches scheduled more than once share the same portion limit.</p></details><h3>Assign portions to the weekly menu</h3><p class="field-note">An assignment replaces the generated meal at that date and time. Assigned portions are total portions for the household; daily nutrition shows the average per person. Pick dates within your selected plan week to see them there.</p><form class="batch-assignment-form" data-schedule-batch="${b.id}"><label>Meal date<input type="date" name="date" value="${esc(date)}" required></label><label>Meal<select name="slot"><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option></select></label><label>Total portions<input type="number" name="portions" min="0.25" step="0.25" value="1" max="${Math.max(c.remaining,0.25)}" required></label><button type="submit" class="secondary" ${c.remaining<=0?'disabled':''}>Assign</button></form><ul class="batch-assignments">${b.assignments.map((a,i)=>`<li>${a.date} · ${a.slot} · ${a.portions} portion${a.portions===1?'':'s'}<button class="lock" data-unassign="${b.id}|${i}" aria-label="Remove assignment for ${a.date} ${a.slot}">× Remove</button></li>`).join('')}</ul>${b.notes?`<p class="field-note">${esc(b.notes)}</p>`:''}<p role="status" class="assignment-status"></p></article>`;}).join(''):'<div class="empty">Create your first batch above.</div>';}
async function load(){try{[products,batches]=await Promise.all([api('/api/products'),api('/api/batches')]);display();if(!document.querySelector('.batch-ingredient'))addRow();document.dispatchEvent(new CustomEvent('gather-batches-updated',{detail:{products,batches}}));}catch(e){status(e.message,true);}}
$('batch-form').addEventListener('input',preview);$('batch-form').addEventListener('change',e=>{if(e.target.matches('.batch-unit')){const label=e.target.closest('.batch-ingredient').querySelector('.conversion-field');label.hidden=!['grams','pieces'].includes(e.target.value);}preview();});
$('add-batch-ingredient').addEventListener('click',()=>addRow());$('batch-ingredients').addEventListener('click',e=>{const b=e.target.closest('.remove-ingredient');if(b){b.closest('.batch-ingredient').remove();preview();}});
$('clear-batch').addEventListener('click',()=>{edit(null);status('Ready for a new batch.');});
$('batch-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const saved=await api('/api/batches',read());await load();edit(saved);status('Batch saved. Assign its meal portions below.');}catch(e){status(e.message,true);}finally{button.disabled=false;}});
$('batch-list').addEventListener('click',async e=>{const b=e.target.closest('[data-edit-batch]');if(b){edit(batches.find(x=>x.id===b.dataset.editBatch));$('batch-name').focus();status('Editing this batch. Existing assignments will be preserved.');return;}const remove=e.target.closest('[data-unassign]');if(remove){const [id,index]=remove.dataset.unassign.split('|');const batch=structuredClone(batches.find(x=>x.id===id));batch.assignments.splice(Number(index),1);try{await api('/api/batches',batch);await load();if(editing?.id===id)editing=batch;}catch(e){remove.closest('article').querySelector('.assignment-status').textContent=e.message;}}});
$('batch-list').addEventListener('submit',async e=>{const form=e.target.closest('[data-schedule-batch]');if(!form)return;e.preventDefault();const batch=structuredClone(batches.find(x=>x.id===form.dataset.scheduleBatch));const values=Object.fromEntries(new FormData(form));batch.assignments.push({date:values.date,slot:values.slot,portions:Number(values.portions)});try{await api('/api/batches',batch);await load();if(editing?.id===batch.id)editing=batch;}catch(e){form.closest('article').querySelector('.assignment-status').textContent=e.message;}});
document.addEventListener('gather-products-updated',()=>load());$('week').addEventListener('change',display);load();
