import {DatabaseSync} from 'node:sqlite';
import {validateProduct} from './products.js';
import {validateBatch} from './batches.js';
import {randomUUID} from 'node:crypto';
export function openDatabase(filename){
 const db=new DatabaseSync(filename);db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, document TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS price_history (id INTEGER PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), snapshot TEXT NOT NULL, recorded_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS batches (id TEXT PRIMARY KEY, document TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);`);
 const decode=row=>row?{...JSON.parse(row.document),id:row.id,createdAt:row.created_at,updatedAt:row.updated_at}:null;
 const store={close:()=>db.close(),list:()=>db.prepare('SELECT * FROM products ORDER BY updated_at DESC').all().map(decode),get:id=>decode(db.prepare('SELECT * FROM products WHERE id=?').get(id)),history:id=>db.prepare('SELECT snapshot, recorded_at FROM price_history WHERE product_id=? ORDER BY id DESC').all(id).map(r=>({...JSON.parse(r.snapshot),recordedAt:r.recorded_at})),save:input=>{
  const p=validateProduct(input),id=p.retailerId,now=new Date().toISOString(),old=decode(db.prepare('SELECT * FROM products WHERE id=?').get(id));
  const price={regularPrice:p.regularPrice,currentPrice:p.currentPrice,discountedPrice:p.discountedPrice,priceContext:p.priceContext,priceSource:p.priceSource,observedAt:p.observedAt};
  const changed=!old||Object.keys(price).some(k=>old[k]!==price[k]);db.exec('BEGIN');try{db.prepare('INSERT INTO products VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET document=excluded.document, updated_at=excluded.updated_at').run(id,JSON.stringify(p),old?.createdAt||now,now);if(changed)db.prepare('INSERT INTO price_history(product_id,snapshot,recorded_at) VALUES(?,?,?)').run(id,JSON.stringify(price),now);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return decode(db.prepare('SELECT * FROM products WHERE id=?').get(id));
 }};
 return Object.assign(store,{listBatches:()=>db.prepare('SELECT * FROM batches ORDER BY updated_at DESC').all().map(decode),saveBatch:input=>{const batch=validateBatch(input,store.list()),id=input.id?String(input.id):randomUUID();if(!/^[a-zA-Z0-9-]{1,80}$/.test(id))throw new Error('Invalid batch ID.');const old=decode(db.prepare('SELECT * FROM batches WHERE id=?').get(id));for(const other of db.prepare('SELECT * FROM batches WHERE id<>?').all(id).map(decode))if(other.assignments.some(a=>batch.assignments.some(b=>a.date===b.date&&a.slot===b.slot)))throw new Error('Another batch already occupies that meal slot. Remove it first.');const now=new Date().toISOString();db.prepare('INSERT INTO batches VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET document=excluded.document,updated_at=excluded.updated_at').run(id,JSON.stringify(batch),old?.createdAt||now,now);return decode(db.prepare('SELECT * FROM batches WHERE id=?').get(id));}});
}
