import test from 'node:test';
import assert from 'node:assert/strict';
import {walmartURL,validateProduct,packageNutrition,parseLabel,parseProductHTML,mergeProductImport} from './products.js';
import {openDatabase} from './database.js';
const item={url:'https://www.walmart.com/ip/seort/18330567070?foo=bar',name:'Waffles',currentPrice:5.82,servingsPerContainer:4,nutrition:{calories:230,protein:20,sodium:350}};
test('refresh replaces pending metadata and fills blanks while preserving saved nutrition including zero',()=>{
 const result=mergeProductImport({name:'Walmart item 172144435 — details pending',currentPrice:null,nutrition:{protein:0,calories:null}}, {name:'Eggs',currentPrice:2,nutrition:{protein:6,calories:70},servingsPerContainer:6});
 assert.equal(result.name,'Eggs');assert.equal(result.currentPrice,2);assert.equal(result.nutrition.protein,0);assert.equal(result.nutrition.calories,70);assert.equal(result.servingsPerContainer,6);
});
test('Walmart links canonicalize and reject unrelated hosts and unsafe URLs',()=>{assert.equal(walmartURL(item.url).retailerId,'18330567070');for(const u of ['http://www.walmart.com/ip/123','https://walmart.com.evil.com/ip/123','https://user@www.walmart.com/ip/123','https://localhost/ip/123','https://www.walmart.com/api/123'])assert.throws(()=>walmartURL(u));});
test('unknown nutrition and prices remain null; zero remains zero',()=>{const p=validateProduct({...item,nutrition:{...item.nutrition,transFat:0}});assert.equal(p.regularPrice,null);assert.equal(p.discountedPrice,null);assert.equal(p.nutrition.transFat,0);assert.equal(p.nutrition.fiber,null);assert.equal(packageNutrition(p).protein,80);assert.equal(packageNutrition(p).fiber,null);});
test('rejects impossible prices and malformed nutrient amounts',()=>{assert.throws(()=>validateProduct({...item,regularPrice:2,discountedPrice:3}));assert.throws(()=>validateProduct({...item,nutrition:{protein:-1}}));assert.throws(()=>validateProduct({...item,nutritionSource:'javascript:alert(1)'}));assert.throws(()=>validateProduct({...item,servingsPerContainer:0}));});
test('label parser distinguishes sodium units and added sugars',()=>{const p=parseLabel('4 servings per container\nServing size 2 waffles (80g)\nCalories 230\nTotal Fat 10g 13%\nTotal Carbohydrate 16g\nSodium 350mg 15%\nTotal Sugars 3g\nIncludes 2g Added Sugars\nProtein 20g');assert.equal(p.nutrition.sodium,350);assert.equal(p.nutrition.addedSugars,2);assert.equal(p.nutrition.sugars,3);assert.equal(p.servingSize,'2 waffles (80g)');assert.equal(p.servingsPerContainer,4);assert.equal(parseLabel('Sodium 15%').nutrition.sodium,undefined);});
test('metadata extraction avoids recommendation products and invented discounts',()=>{const h=`<script type="application/ld+json">${JSON.stringify([{ '@type':'Product',name:'Other',sku:'1',offers:{price:1}},{'@type':'Product',name:'Waffles',sku:'18330567070',offers:{price:'5.82',priceCurrency:'USD'}}])}</script>`;const p=parseProductHTML(h,item.url);assert.equal(p.name,'Waffles');assert.equal(p.currentPrice,5.82);assert.equal(p.discountedPrice,undefined);assert.equal(parseProductHTML('<html>Robot check</html>',item.url).name,'');});
test('SQLite upserts same item, saves price history, and preserves nutrition',()=>{const db=openDatabase(':memory:');try{const p=db.save(item);db.save({...p,name:'New name'});assert.equal(db.list().length,1);assert.equal(db.history(p.id).length,1);db.save({...p,currentPrice:5});assert.equal(db.history(p.id).length,2);assert.equal(db.get(p.id).nutrition.sodium,350);}finally{db.close();}});
test('Walmart page data imports only the requested item, prices and image label source',()=>{const data={props:{pageProps:{initialData:{data:{product:{usItemId:'824841960',name:'Lean beef',brand:'Fresh Ground Beef',priceInfo:{currentPrice:{price:8.47,currencyUnit:'USD'},wasPrice:null}},idml:{specifications:[{name:'Weight',value:'1 lb'},{name:'Nutrition facts label image',value:'https://example.com/label.jpg'}]}}}}}};const html=`<script id="__NEXT_DATA__" type="application/json">${JSON.stringify(data)}</script>`;const p=parseProductHTML(html,'https://www.walmart.com/ip/824841960');assert.equal(p.name,'Lean beef');assert.equal(p.currentPrice,8.47);assert.equal(p.packageSize,'1 lb');assert.equal(p.nutritionSource,'https://example.com/label.jpg');assert.equal(p.discountedPrice,undefined);assert.equal(Object.keys(p.nutrition).length,0);assert.equal(parseProductHTML(html,'https://www.walmart.com/ip/999').name,'');});
test('saved products retain recognized text and extraction provenance',()=>{const db=openDatabase(':memory:');try{const p=db.save({...item,extraction:{method:'Local OCR',confidence:85,text:'Calories 230\nProtein 20g',warnings:['Review label'],extractedAt:'2026-10-03T23:00:00.000Z'}});assert.equal(db.get(p.id).extraction.confidence,85);assert.equal(db.get(p.id).extraction.text,'Calories 230\nProtein 20g');assert.deepEqual(db.get(p.id).extraction.warnings,['Review label']);}finally{db.close();}});
