import {nutritionFields,parseLabel,packageNutrition,walmartURL,mergeProductImport} from './products.js';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n===null||n===undefined?'Not shown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const numericFields=['regularPrice','currentPrice','discountedPrice','servingsPerContainer'];
const textFields=['url','name','brand','packageSize','servingSize','priceContext','priceSource','nutritionSource','notes'];
let products=[],draftObservedAt=null,draftExtraction=null;
const field=(key,label,type='text')=>`<label>${label}<input id="product-${key}" name="${key}" type="${type}" ${type==='number'?'min="0" max="10000000" step="any"':''} ${['name','url'].includes(key)?'required':''}></label>`;
$('products').innerHTML=`<div class="library-heading"><div><p class="eyebrow">KNOW WHAT’S IN YOUR FOOD</p><h2>Your food library</h2></div><button class="secondary" id="export-products">Export JSON ↗</button></div><p class="view-intro">Save Walmart products, package prices, and nutrition per serving. Unknown values stay blank. Use these products in Batch Meals to calculate nutrition and cost per portion.</p>
<details class="product-panel" id="product-editor"><summary class="product-editor-title">＋ Add or update a Walmart product</summary><form id="product-form">
<div class="import-row">${field('url','Walmart product link','url')}<button type="button" class="secondary" id="import-product">Read link ↗</button></div><p id="import-status" role="status" aria-live="polite" hidden></p><a id="import-label-link" class="import-label-link" target="_blank" rel="noopener noreferrer" hidden>Open nutrition label / source ↗</a><button type="button" class="secondary" id="read-label-image" hidden>Read nutrition image</button><p class="field-note">Read link automatically reads available nutrition-label images locally. Image reading can take up to 90 seconds on first use. Review extracted values before saving.</p>
<div class="two-fields">${field('name','Item name')}${field('brand','Brand')}</div>${field('packageSize','Package size / count')}
<h3>Package price · USD</h3><div class="price-fields">${field('regularPrice','Before discount / “was” price','number')}${field('currentPrice','Current listed price','number')}${field('discountedPrice','Discounted price (if shown)','number')}</div><p class="field-note">Prices are for the whole package, before tax or fees. Leave “was” and discounted prices blank when no discount is shown.</p>${field('priceContext','Store / seller / pickup or delivery context')}${field('priceSource','Price source link','url')}
<h3>Nutrition facts · per serving</h3><div class="two-fields">${field('servingSize','Serving size, e.g. 2 waffles (80 g)')}${field('servingsPerContainer','Servings per container','number')}</div><div class="nutrition-inputs">${nutritionFields.map(([k,l,u])=>field(k,`${l} · ${u}`,'number')).join('')}</div>${field('nutritionSource','Nutrition source link','url')}
<details class="paste-label"><summary>Review extracted text / paste nutrition label</summary><label>Label text<textarea id="label-text" rows="6" placeholder="4 servings per container&#10;Serving size 2 waffles (80g)&#10;Calories 230&#10;Total Fat 10g&#10;Sodium 350mg"></textarea></label><button type="button" class="secondary" id="parse-label">Fill from label text</button><p class="field-note">Recognized image text appears here for review. Only explicitly labeled amounts are filled; check them against the original image.</p></details>
<label>Notes<textarea id="product-notes" rows="2"></textarea></label><label class="review-check"><input type="checkbox" id="product-reviewed"> I reviewed these prices and nutrition values</label><div class="product-actions"><button class="primary" type="submit">Save product <span>＋</span></button><button class="secondary" type="button" id="new-product">Clear form</button></div>
<p id="product-status" role="status" aria-live="polite"></p></form></details>
<div class="library-heading"><h2>Saved products <span id="product-count"></span></h2><label class="search-label">Search library<input id="product-search" type="search" placeholder="Name, brand, or item ID"></label></div><div id="product-list"></div>`;
async function api(url,body){const response=await fetch(url,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(url.includes('/import')||url.includes('/read-label')?100000:20000)});let data;try{data=await response.json();}catch{throw new Error('The local server returned an unreadable response. Restart the app server and try again.');}if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
function status(message,error=false){$('product-status').textContent=message;$('product-status').className=error?'product-error':'product-success';}
function importStatus(message,error=false){const el=$('import-status');el.hidden=false;el.textContent=message;el.className=error?'notice product-error':'notice product-success';}
function setDraft(p){$('product-form').reset();for(const k of [...textFields,...numericFields])$(`product-${k}`).value=p[k]??'';for(const [k]of nutritionFields)$(`product-${k}`).value=p.nutrition?.[k]??'';$('product-reviewed').checked=Boolean(p.reviewed);draftObservedAt=p.observedAt||null;draftExtraction=p.extraction||null;$('label-text').value=p.extraction?.text||'';const label=$('import-label-link');label.hidden=!p.nutritionSource;if(p.nutritionSource)label.href=p.nutritionSource;else label.removeAttribute('href');$('read-label-image').hidden=!/^https:\/\/(?:images\.salsify\.com|i5\.walmartimages\.com|i5\.walmartimages\.ca)\//i.test(p.nutritionSource||'');}
function readDraft(){const p={nutrition:{},observedAt:draftObservedAt,extraction:draftExtraction,reviewed:$('product-reviewed').checked};for(const k of textFields)p[k]=$(`product-${k}`).value;for(const k of numericFields)p[k]=$(`product-${k}`).value;for(const [k]of nutritionFields)p.nutrition[k]=$(`product-${k}`).value;return p;}
function display(){const q=$('product-search').value.toLowerCase();$('product-count').textContent=`(${products.length})`;const visible=products.filter(p=>`${p.name} ${p.brand} ${p.id}`.toLowerCase().includes(q));$('product-list').innerHTML=visible.length?visible.map(p=>{const packageFacts=packageNutrition(p),saving=p.regularPrice!==null&&p.discountedPrice!==null?p.regularPrice-p.discountedPrice:null;const price=p.currentPrice??p.discountedPrice??p.regularPrice;return `<article class="product-panel saved-product"><div class="product-card-top"><div><p class="eyebrow">${esc(p.brand||'WALMART')} · ITEM ${esc(p.id)}</p><h3>${esc(p.name)}</h3><p class="field-note">${esc(p.packageSize)} · ${p.reviewed?'Reviewed by you':'Needs review'}</p></div><button class="secondary" data-edit="${p.id}">Edit</button></div><div class="price-summary"><div><small>Current listed</small><strong>${money(p.currentPrice)}</strong></div><div><small>Before discount</small><strong>${money(p.regularPrice)}</strong></div><div><small>Discounted</small><strong>${money(p.discountedPrice)}</strong></div></div><p class="field-note">${saving!==null?`Savings: ${money(saving)}. `:''}${price!==null&&p.servingsPerContainer?`Listed cost per serving: ${money(price/p.servingsPerContainer)}. `:''}${esc(p.priceContext)}</p><p><strong>${p.servingsPerContainer??'Unknown'} servings</strong> · ${esc(p.servingSize||'Serving size unknown')}</p><details><summary>Nutrition label & package totals</summary><table class="nutrition-table"><thead><tr><th>Nutrient</th><th>Per serving</th><th>Whole package*</th></tr></thead><tbody>${nutritionFields.map(([k,l,u])=>`<tr><th>${l}</th><td>${p.nutrition[k]===null?'Unknown':`${p.nutrition[k]} ${u}`}</td><td>${packageFacts[k]===null?'Unknown':`${Number(packageFacts[k].toFixed(2))} ${u}`}</td></tr>`).join('')}</tbody></table><p class="field-note">*Calculated from the label servings per container; label rounding may affect totals.</p></details><div class="product-sources"><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Walmart item ↗</a>${p.nutritionSource?`<a href="${esc(p.nutritionSource)}" target="_blank" rel="noopener noreferrer">Nutrition source ↗</a>`:''}<a href="${esc(p.priceSource)}" target="_blank" rel="noopener noreferrer">Price source ↗</a><button class="lock" data-history="${p.id}">Price history</button></div><p class="field-note">${p.observedAt?`Source checked ${new Date(p.observedAt).toLocaleString()}. `:''}Saved ${new Date(p.updatedAt).toLocaleString()}.</p>${p.notes?`<p class="field-note">${esc(p.notes)}</p>`:''}<div id="history-${p.id}"></div></article>`;}).join(''):'<div class="empty">No products here yet. Paste a Walmart link above to start.</div>';}
async function load(){try{products=await api('/api/products');if(!products.length)$('product-editor').open=true;display();document.dispatchEvent(new CustomEvent('gather-products-updated',{detail:{products}}));}catch(e){$('product-editor').open=true;status(`Could not load the database: ${e.message}`,true);}}
$('product-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await api('/api/products',readDraft());status('Product saved to your database. Reusing the same Walmart item updates its record and preserves price history.');await load();}catch(e){status(e.message,true);}finally{button.disabled=false;}});
$('import-product').addEventListener('click',async()=>{const button=$('import-product');button.disabled=true;button.setAttribute('aria-busy','true');const original=button.textContent;button.textContent='Reading…';$('read-label-image').disabled=true;importStatus('Reading item details and nutrition image… first use may take up to 90 seconds.');try{const identity=walmartURL($('product-url').value);const existing=products.find(p=>p.id===identity.retailerId);const result=await api('/api/products/import',{url:document.getElementById('product-url').value});setDraft(mergeProductImport(existing,result.draft));importStatus(result.message+(existing?' Saved nutrition values were preserved; fresh prices and missing details are ready for review. Save to update your item.':''));}catch(e){importStatus(['TimeoutError','AbortError'].includes(e.name)?'The request timed out. Check that the app server is running, then retry or enter details manually.':e.message==='Failed to fetch'?'Cannot reach the local app server. Restart it and retry.':e.message,true);}finally{button.disabled=false;button.removeAttribute('aria-busy');button.textContent=original;$('read-label-image').disabled=false;}});
async function fillImage(){const label=await api('/api/products/read-label',{url:$('product-nutritionSource').value});let count=0;for(const [k,v]of Object.entries(label.nutrition)){if($(`product-${k}`).value===''){$(`product-${k}`).value=v;count++;}}if(!$('product-servingSize').value&&label.servingSize)$('product-servingSize').value=label.servingSize;if(!$('product-servingsPerContainer').value&&label.servingsPerContainer)$('product-servingsPerContainer').value=label.servingsPerContainer;draftExtraction=label.extraction;$('label-text').value=label.extraction.text;if(count)$('product-reviewed').checked=false;importStatus(`${count} blank nutrition fields filled from the image. Existing values were preserved. Compare values with the source before saving. ${label.extraction.warnings.join(' ')}`);}
$('read-label-image').addEventListener('click',async()=>{const button=$('read-label-image');button.disabled=true;$('import-product').disabled=true;button.textContent='Reading label…';importStatus('Reading nutrition image locally… first use may take up to 90 seconds.');try{await fillImage();}catch(e){importStatus(`Could not read the label: ${e.message}`,true);}finally{button.disabled=false;$('import-product').disabled=false;button.textContent='Read nutrition image';}});
$('parse-label').addEventListener('click',()=>{const parsed=parseLabel($('label-text').value);for(const [k,v]of Object.entries(parsed.nutrition))$(`product-${k}`).value=v;if(parsed.servingSize)$('product-servingSize').value=parsed.servingSize;if(parsed.servingsPerContainer)$('product-servingsPerContainer').value=parsed.servingsPerContainer;status(`Filled ${Object.keys(parsed.nutrition).length} recognized nutrient fields. Verify against the label before saving.`);});
$('new-product').addEventListener('click',()=>{setDraft({});$('import-status').hidden=true;status('Ready for a new product.');});
$('product-search').addEventListener('input',display);
$('product-list').addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]');if(edit){$('product-editor').open=true;setDraft(products.find(p=>p.id===edit.dataset.edit));status('Editing saved product. Saving will update the same item.');$('product-url').focus();return;}const h=e.target.closest('[data-history]');if(h){try{const history=await api(`/api/products/${h.dataset.history}/history`);$(`history-${h.dataset.history}`).innerHTML=`<div class="history-list">${history.map(x=>`<p>${esc(new Date(x.recordedAt).toLocaleString())} · Listed ${money(x.currentPrice)} · Was ${money(x.regularPrice)} · Discounted ${money(x.discountedPrice)}<br>${esc(x.priceContext)}</p>`).join('')}</div>`;}catch(e){$('product-editor').open=true;status(e.message,true);}}});
$('export-products').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(products,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gather-products.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
load();
